import { useState } from "react";
import { Routes, Route, NavLink, useNavigate } from "react-router-dom";
import { Home, Users, Clock3, Settings, Search, ChevronLeft, Bell, AlertTriangle, Heart, Sparkles, MessageCircle, Pencil, Check, CalendarDays } from "lucide-react";
import { customers, nailImages } from "./data";

function Shell({children, title, back=false}:{children:React.ReactNode;title?:string;back?:boolean}){
 const nav=useNavigate();
 return <div className="phone-shell">
  <header className="topbar">{back?<button className="icon-btn" onClick={()=>nav(-1)} aria-label="戻る"><ChevronLeft/></button>:<div className="brand-mark">A</div>}<div className="top-title">{title||"Atelier Note"}</div><button className="icon-btn"><Bell/></button></header>
  <main className="content">{children}</main>
  <nav className="bottom-nav">
   <NavLink to="/"><Home/><span>ホーム</span></NavLink><NavLink to="/customers"><Users/><span>顧客</span></NavLink><a><Clock3/><span>履歴</span></a><a><Settings/><span>その他</span></a>
  </nav>
 </div>
}
function Avatar({initial,big=false}:{initial:string;big?:boolean}){return <div className={big?"avatar big":"avatar"}>{initial}</div>}
function Metric({value,label,tone}:{value:string;label:string;tone?:string}){return <div className={'metric '+(tone||'')}><strong>{value}</strong><span>{label}</span></div>}
function Dashboard(){const nav=useNavigate();const [q,setQ]=useState("佐藤");return <Shell><section className="hello"><div><small>2026年8月28日</small><h1>おはようございます、Rinaさん</h1></div><Avatar initial="RN"/></section><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="顧客検索"/><button onClick={()=>nav('/customers')}>検索</button></div><div className="metrics"><Metric value="128" label="登録顧客"/><Metric value="34" label="今月の来店"/><Metric value="5" label="注意事項あり" tone="warn"/></div><SectionTitle title="最近更新した顧客" action="すべて見る"/><div className="customer-stack">{customers.slice(0,2).map(c=><CustomerCard key={c.id} c={c}/>)}</div><SectionTitle title="最近のデザイン"/><div className="photo-row">{nailImages.map((x,i)=><img key={x} src={x} alt={`ネイルデザイン ${i+1}`}/>)}</div></Shell>}
function SectionTitle({title,action}:{title:string;action?:string}){return <div className="section-title"><h2>{title}</h2>{action&&<span>{action}</span>}</div>}
function CustomerCard({c}:{c:typeof customers[number]}){const nav=useNavigate();return <button className="customer-card" onClick={()=>nav('/customers/customer-001')}><Avatar initial={c.initial}/><div className="customer-main"><strong>{c.name}</strong><small>{c.kana}</small><div className="tags">{c.tags.map(t=><i key={t}>{t}</i>)}</div></div><div className="customer-meta">{c.alert&&<AlertTriangle/>}<b>{c.visits}回</b><small>最終 {c.last}</small></div></button>}
function Customers(){return <Shell title="顧客"><div className="page-head"><div><small>検索結果</small><h1>「佐藤」の顧客</h1></div><span className="count">1名</span></div><div className="search static"><Search/><span>佐藤</span></div><div className="filter-row"><button className="selected">すべて</button><button>注意事項あり</button><button>最近来店</button></div><CustomerCard c={customers[0]}/><div className="subtle-note">固定デモデータを表示しています</div></Shell>}
function Safety(){return <div className="safety"><div className="safety-icon"><AlertTriangle/></div><div><small>重要な注意事項</small><strong>アクリル系商材に注意</strong><p>過去に赤みが出たため、使用前に必ず状態を確認してください。</p></div></div>}
function CustomerDetail(){const nav=useNavigate();return <Shell title="顧客カルテ" back><div className="profile"><Avatar initial="MS" big/><div><h1>佐藤 美咲</h1><p>担当 Rina ・ 来店12回</p><span><CalendarDays/>最終来店 2026年8月22日</span></div></div><Safety/><section className="card"><div className="card-title"><Heart/>好み・デザイン</div><div className="label">好きな色</div><div className="color-chips"><span>ベージュ</span><span>ボルドー</span><span>くすみピンク</span></div><div className="two"><div><div className="label">好きな系統</div><b>シンプル・上品</b></div><div><div className="label">爪の形</div><b>オーバル</b></div></div></section><section className="card"><div className="card-title"><Sparkles/>爪の状態</div><p>右手人差し指が薄くなりやすい</p><div className="note">強いプッシャー圧を避け、ベースを薄く二度塗りする。</div></section><section className="card conversation"><div className="card-title"><MessageCircle/>前回の会話</div><p>9月に京都旅行を予定。秋色ネイルを検討中。</p><div className="next-topic"><small>次回聞きたいこと</small><b>京都旅行の予定</b></div><button className="edit-btn" onClick={()=>nav('/customers/customer-001/edit')}><Pencil/>会話メモを編集</button></section><SectionTitle title="過去の施術デザイン"/><div className="photo-row big-photos">{nailImages.map((x,i)=><div className="photo-card" key={x}><img src={x} alt={`過去の施術 ${i+1}`}/><small>{['8月22日','7月19日','6月15日'][i]}</small></div>)}</div></Shell>}
function Edit(){const nav=useNavigate();const [saved,setSaved]=useState(false);const save=()=>{setSaved(true);setTimeout(()=>nav('/customers/customer-001'),1300)};return <Shell title="会話メモを編集" back><div className="edit-profile"><Avatar initial="MS"/><div><strong>佐藤 美咲</strong><small>最終来店 8月22日</small></div></div><div className="form-card"><label>前回の会話要約<textarea defaultValue="9月に京都旅行を予定。秋色ネイルを検討中。"/></label><label>次回聞きたいこと<input defaultValue="京都旅行の予定"/></label><label>接客時の注意<textarea defaultValue="強いプッシャー圧を避ける"/></label></div><div className="sticky-actions"><button className="cancel" onClick={()=>nav(-1)}>キャンセル</button><button className="save" onClick={save}><Check/>保存する</button></div>{saved&&<div className="toast"><Check/>カルテを保存しました</div>}</Shell>}
export function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/customers" element={<Customers/>}/><Route path="/customers/customer-001" element={<CustomerDetail/>}/><Route path="/customers/customer-001/edit" element={<Edit/>}/></Routes>}
